apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: udnximdrr-go 
  janus-idp.io/tekton: udnximdrr-go
  backstage.io/kubernetes-id: udnximdrr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: udnximdrr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  